### PR TITLE
add protobuf schema evoluation

### PR DESCRIPTION
**Pull request by kaori-seasons**
related to [issue-30](https://github.com/apache/rocketmq-schema-registry/issues/30)

### CODE REVIEW

**Comment by kaori-seasons** [comment]
Since the proto file needs to generate ``` Validation``` dynamically I will fix this after generating locally

**Comment by MatrixHB** [comment]
@complone Hello, thank you very much for contributing this PR, but before you further optimize, I need to confirm whether you have any misunderstanding about the compatibility validation of protobuf? 
The so-called compatibility validation here focuses on compatibility, that is, comparing the updated protobuf schema with the previous version of protobuf schema, whether its changes will make the production and consumption of messages incompatible.

However, judging from the code you submitted, it seems to focus on the verification of fields, field value range, regular matching, etc. IMO, the schema registry does not intend to cover the logic of this part, which is more business oriented.

If it's because I don't understand your original intention, we can continue to discuss it. Thank you very much.

**Comment by MatrixHB** [comment]
You can take a look at how _kafka-schema-registry_ deals with protobuf compatibility validation. It focuses on change between two versions of protobuf schema.

https://github.com/confluentinc/schema-registry/blob/79a27211eb44b3df90ad3bdcb7f64ac48c2024ba/protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java#L1741-L1770

**Comment by kaori-seasons** [comment]
> @complone您好，非常感谢您贡献这个PR，但是在您进一步优化之前，我需要确认您是否对protobuf的兼容性验证有任何误解？ 这里所谓的兼容性验证关注的是兼容性，也就是比较更新后的protobuf schema和之前版本的protobuf schema，其变化是否会使得消息的生产和消费不兼容。
> 
> 但是，从你提交的代码来看，它似乎侧重于对字段、字段值范围、正则匹配等的验证。IMO，schema 注册中心并不打算涵盖这部分的逻辑，它更面向业务。
> 
> 如果是我不明白你的初衷，我们可以继续讨论。非常感谢。

By referring to Avro's verification logic, I found that protobuf does not have a related comparison API. In the process of avro own implementation, tracking the relevant details is to make a recursive comparison between the schema to be verified and the set of existing schemas. But the [generate method](https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/io/parsing/ResolvingGrammarGenerator.java#L53) is not reflected


Thanks a lot for your suggestion here is what I misunderstood. I will try to make changes based on the information you provide

**Comment by MatrixHB** [comment]
> > @complone您好，非常感谢您贡献这个PR，但是在您进一步优化之前，我需要确认您是否对protobuf的兼容性验证有任何误解？ 这里所谓的兼容性验证关注的是兼容性，也就是比较更新后的protobuf schema和之前版本的protobuf schema，其变化是否会使得消息的生产和消费不兼容。
> > 但是，从你提交的代码来看，它似乎侧重于对字段、字段值范围、正则匹配等的验证。IMO，schema 注册中心并不打算涵盖这部分的逻辑，它更面向业务。
> > 如果是我不明白你的初衷，我们可以继续讨论。非常感谢。
> 
> By referring to Avro's verification logic, I found that protobuf does not have a related comparison API. In the process of avro own implementation, tracking the relevant details is to make a recursive comparison between the schema to be verified and the set of existing schemas. But the [generate method](https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/io/parsing/ResolvingGrammarGenerator.java#L53) is not reflected
> 
> Thanks a lot for your suggestion here is what I misunderstood. I will try to make changes based on the information you provide

@ferrirW Is schema registry suitable to cover the generate logic？ [generate method](https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/io/parsing/ResolvingGrammarGenerator.java#L53)

**Pull request closed without merging**
