### PR TITLE
add http client for rocketmq schema registry

### LINKED ISSUE #6: Add a http client for rocketmq-schema-registry
Add a normal schema registry client to provide schema CRUD options.

### PR DESCRIPTION
**Pull request by humkum**
close https://github.com/apache/rocketmq-schema-registry/issues/6

### CODE REVIEW

**Comment by ferrirW** [comment]
We should also add the following capabilities in the future: 
1. serialize / deserialize wrapper
2. Compatibility and format check util

**Comment by MatrixHB** [comment]
I wonder what's the meaning of "NormalSchemaRegistryClient", and what kind of  SchemaRegistryClient will be extended in the future?

**Comment by humkum** [comment]
> I wonder what's the meaning of "NormalSchemaRegistryClient", and what kind of SchemaRegistryClient will be extended in the future?

Well. There are no other ideas at present, this interface is reserved for the convenience of future expansion

**Comment by humkum** [comment]
> We should also add the following capabilities in the future:
> 
> 1. serialize / deserialize wrapper
> 2. Compatibility and format check util

I will do this

**Review by ferrirW — APPROVED** [review]

**Pull request closed without merging**
