### PR TITLE
simplify schema record id to user

### PR DESCRIPTION
**Pull request by ferrirW**
id + version => schemaRecordId

### CODE REVIEW

**Comment by MatrixHB** [comment]
@ferrirW please pay attention to the CI build error

**Comment by MatrixHB** [comment]
The schemaRecordId is returned to users but it is not shown where this recordId needs to be used. 
I think the way to get schema is still by SchemaId or by SchemaVersion, not by recordId.

**Comment by ferrirW** [comment]
> The schemaRecordId is returned to users but it is not shown where this recordId needs to be used. I think the way to get schema is still by SchemaId or by SchemaVersion, not by recordId.

I can add it to the document, SchemaRecordId is consisted of SchemaId and SchemaVersion with customed snowflake algorithm.

And Actually, the user doesn't need to care about the RecordId, it's more about the Client using the RecordId to serialize the message. Old version (SchemaId and SchemaVersion) will taking too much space(128B), new version (SchemaRecordId) only use 64B. @MatrixHB

**Comment by MatrixHB** [comment]
> > The schemaRecordId is returned to users but it is not shown where this recordId needs to be used. I think the way to get schema is still by SchemaId or by SchemaVersion, not by recordId.
> 
> I can add it to the document, SchemaRecordId is consisted of SchemaId and SchemaVersion with customed snowflake algorithm.
> 
> And Actually, the user doesn't need to care about the RecordId, it's more about the Client using the RecordId to serialize the message. Old version (SchemaId and SchemaVersion) will taking too much space(128B), new version (SchemaRecordId) only use 64B. @MatrixHB

Got it. So we need to add a method to get schema by RecordId in `SchemaRegistryClient`,  in order to support message ser/de, right?

**Comment by ferrirW** [comment]
> > > The schemaRecordId is returned to users but it is not shown where this recordId needs to be used. I think the way to get schema is still by SchemaId or by SchemaVersion, not by recordId.
> > 
> > 
> > I can add it to the document, SchemaRecordId is consisted of SchemaId and SchemaVersion with customed snowflake algorithm.
> > And Actually, the user doesn't need to care about the RecordId, it's more about the Client using the RecordId to serialize the message. Old version (SchemaId and SchemaVersion) will taking too much space(128B), new version (SchemaRecordId) only use 64B. @MatrixHB
> 
> Got it. So we need to add a method to get schema by RecordId in `SchemaRegistryClient`, in order to support message ser/de, right?

Yes, this method will be add by @humkum later, and client serde will also be modified.

**Pull request merged**
